name: Test Espressif on various Docker containers

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  espressif_test:
    name: Test Espressif on Docker container
    runs-on: espressif/idf:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Espressif
        run: IDE/Espressif/ESP-IDF/compileAllExamples.sh
