# This workflow tests out new libraries with existing OpenWrt builds to check
# there aren't any compatibility issues. Take a look at Docker/OpenWrt/README.md
name: OpenWrt test
concurrency:
    group: ${{ github.head_ref || github.run_id }}
#    cancel-in-progress: true

on:
    push:
#        branches: [ 'master', 'main', 'release/**' ]
        branches: [ '*' ]
    pull_request:
        branches: [ '*' ]

jobs:
    build_library:
        name: Compile latest libwolfssl.so
        runs-on: ubuntu-latest
        container:
            image: alpine:latest
        steps:
            - name: Install required tools
              run: apk add argp-standalone asciidoc bash bc binutils bzip2 cdrkit coreutils diffutils elfutils-dev findutils flex musl-fts-dev g++ gawk gcc gettext git grep intltool libxslt linux-headers make musl-libintl musl-obstack-dev ncurses-dev openssl-dev patch perl python3-dev rsync tar unzip util-linux wget zlib-dev autoconf automake libtool
            - uses: actions/checkout@v3
            - name: Compile libwolfssl.so
              run: ./autogen.sh && ./configure --enable-all && make
            - name: Upload libwolfssl.so
              uses: actions/upload-artifact@v3
              with:
                name: libwolfssl.so
                path: src/.libs/libwolfssl.so.35.3.0
                retention-days: 1
    compile_container:
        name: Build OpenWrt test container
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: docker/setup-qemu-action@v2
            - uses: docker/setup-buildx-action@v2
            -
              name: Build but dont push
              uses: docker/build-push-action@v3
              with:
                  context: .
                  platforms: linux/amd64
                  file: Docker/OpenWrt/Dockerfile
                  push: false
                  tags: openwrt-test:latest
#                  cache-from: type=registry,ref=openwrt-test:latest
#                  cache-to: type=inline
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
