name: wolfSSL CI tests
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ '*' ]
#    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

jobs:
    call_workflows:
        strategy:
            matrix:
                workflow: [ docker-Espressif, multi-compiler, docker-OpenWrt, os-check ]
        uses: ./.github/workflows/${{ matrix.workflow }}.yml
