name: wolfSSL CI tests
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ '*' ]
#    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

jobs:
    call_workflows:
        strategy:
            matrix:
                workflow: [ "docker-Espressif.yml", "multi-compiler.yml", "docker-OpenWrt.yml", "os-check.yml" ]
        uses: ./.github/workflows/${{ matrix.workflow }}
