name: Test builds with multiple compilers and versions
concurrency:
  group: ${{ github.ref }}

on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

jobs:
  gcc_latest:
    name: Use GCC-latest
    runs-on: ubuntu-latest
    container:
      image: gcc:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: ./autogen.sh && ./configure && make && make dist
  gcc_12.2:
    name: Use GCC-12.2
    runs-on: ubuntu-latest
    container:
      image: gcc:12.2
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: ./autogen.sh && ./configure && make && make dist
