name: Multiple compilers and versions
concurrency:
  group: ${{ github.ref }}

on:
  push:
    branches: [ '*' ]
#    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

jobs:
  my_matrix:
    name: Test matrix
    strategy:
      matrix:
        CC: [ gcc, clang ]
        include:
          - gcc:
            CXX: g++
          - clang:
            CXX: clang++
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        env:
            CC: ${{ matrix.CC }}
            CXX: ${{ matrix.CXX }}
        run: ./autogen.sh && ./configure && make && make dist
  clang-latest:
    name: Clang
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        env:
            CC: clang
            CXX: clang++
        run: ./autogen.sh && ./configure && make && make dist
  gcc-latest:
    name: GCC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        env:
            CC: gcc
            CXX: g++
        run: ./autogen.sh && ./configure && make && make dist
  gcc-12_2:
    name: GCC-12_2
    runs-on: ubuntu-latest
    container:
      image: gcc:12.2
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: ./autogen.sh && ./configure && make && make dist
