name: Multiple compilers and versions
concurrency:
  group: ${{ github.ref }}

on:
  push:
    branches: [ '*' ]
#    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

jobs:
  my_matrix:
    name: Test matrix
    strategy:
      matrix:
        CC: [ gcc, gcc-9, gcc-10, gcc-11, gcc-12, clang, clang-12, clang-13, clang-14, ]
        include:
          - gcc:
            CXX: g++
          - gcc-9:
            CXX: g++-9
          - gcc-10:
            CXX: g++-10
          - gcc-11:
            CXX: g++-11
          - gcc-12:
            CXX: g++-12
          - clang:
            CXX: clang++
          - clang-12:
            CXX: clang++-12
          - clang-13:
            CXX: clang++-13
          - clang-14:
            CXX: clang++-14
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        env:
            CC: ${{ matrix.CC }}
            CXX: ${{ matrix.CXX }}
        run: ./autogen.sh && ./configure && make && make dist
