name: CI-Coverity-Basic
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch: 
  
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Configure wolfSSL
        run:
          ./autogen.sh
          ./configure --enable-all        
      - name: Coverity Scan
        uses: synopsys-sig/synopsys-action@v1.13.0
        with:
          ### SCANNING: Required fields
          coverity_url: ${{ vars.COVERITY_URL }}
          coverity_user: ${{ vars.COVERITY_USER }}
          coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
          
          ### Coverity Connect users - Uncomment below
          coverity_local: true
               
          ### PULL REQUEST COMMENTS: Uncomment below to enable
          coverity_prComment_enabled: true
          github_token: ${{ secrets.GITHUB_TOKEN }} # Required when PR comments is enabled  
